import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { createClient } from "@/lib/supabase/server";
import { signOut } from "@/app/admin/login/actions";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { artverdImages } from "@/lib/artverdAssets";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const rawAvatarUrl = user?.user_metadata?.avatar_url as string | undefined;
  const avatarUrl = rawAvatarUrl
    ? `/api/avatar?url=${encodeURIComponent(rawAvatarUrl)}`
    : undefined;
  const displayName =
    (user?.user_metadata?.full_name as string | undefined) ||
    (user?.user_metadata?.name as string | undefined);

  return (
    <>
      <header className="bg-card border-b">
        <nav className="flex h-14 items-center justify-between gap-6 px-4">
          <div className="flex items-center gap-6 py-1">
            <Link
              href="/"
              className="flex shrink-0 items-center"
              aria-label="Go to home"
            >
              <Image
                src={artverdImages.logo}
                alt="Art Verd"
                width={640}
                height={296}
                className="h-12 w-auto"
                priority
              />
            </Link>
            <Link
              href="/admin"
              className="text-muted-foreground hover:text-foreground text-sm font-medium"
            >
              Next Bouquet AI
            </Link>
          </div>
          <div className="flex items-center gap-3">
            {user ? (
              <>
                {(avatarUrl || displayName) && (
                  <span className="text-muted-foreground flex items-center gap-2 text-sm">
                    {avatarUrl && (
                      <Avatar className="h-8 w-8">
                        <AvatarImage
                          src={avatarUrl}
                          alt={displayName ?? "User avatar"}
                        />
                        <AvatarFallback>
                          {displayName?.charAt(0)?.toUpperCase() ?? "?"}
                        </AvatarFallback>
                      </Avatar>
                    )}
                    {displayName && (
                      <span className="hidden sm:inline">{displayName}</span>
                    )}
                  </span>
                )}
                <form action={signOut}>
                  <Button type="submit" variant="ghost" size="sm">
                    Sign out
                  </Button>
                </form>
              </>
            ) : (
              <Button asChild variant="ghost" size="sm">
                <Link href="/admin/login">Login</Link>
              </Button>
            )}
          </div>
        </nav>
      </header>
      {children}
      <Analytics />
      <SpeedInsights />
    </>
  );
}
